
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Image generation flow for social media posts, with optional text overlay,
 * considering niche, category, image type, post topic, visual description, and overlay text styling
 * for highly personalized results.
 *
 * - generatePostImage - A function that handles the image generation process.
 * - GeneratePostImageInput - The input type for the generatePostImage function.
 * - GeneratePostImageOutput - The return type for the generatePostImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePostImageInputSchema = z.object({
  imageVisualPrompt: z
    .string()
    .describe('A detailed description of what the image should visually depict.'),
  overlayText: z
    .string()
    .optional() 
    .describe('The AI-generated hook or short text to prominently display on the generated image. If empty, no text will be overlaid.'),
  niche: z.string().describe('The niche of the post (e.g., Food, Travel, Technology). This is required.'),
  category: z.string().describe('The category of the post (e.g., Recipe, Landscape, Product Review). This is required.'),
  imageType: z.string().describe('The desired artistic style of the image (e.g., Photography, Illustration, Modern Design). This is required.'),
  postTopic: z.string().describe('The original topic or idea of the social media post, for broader context.'),
  postType: z.string().optional().describe('The type of the post (e.g., Tips, Educational, Promotional) for additional context.'),
  overlayFontStyle: z.string().optional().describe('The desired font style for the overlay text (e.g., Modern & Clean, Elegant Script, Magazine Headline).'),
  overlayAlignment: z.string().optional().describe('The alignment of the overlay text on the image (e.g., Top Left, Middle Center, Bottom Right).'),
  overlayFontSize: z.string().optional().describe('The relative font size for the overlay text (e.g., Small, Medium, Large, Extra Large).'),
});
export type GeneratePostImageInput = z.infer<typeof GeneratePostImageInputSchema>;

const GeneratePostImageOutputSchema = z.object({
  imageUri: z
    .string()
    .describe(
      'The data URI of the generated image for the social media post. The data URI must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // KEEP THIS COMMENT
    ),
});
export type GeneratePostImageOutput = z.infer<typeof GeneratePostImageOutputSchema>;

export async function generatePostImage(input: GeneratePostImageInput): Promise<GeneratePostImageOutput> {
  return generatePostImageFlow(input);
}

const generatePostImageFlow = ai.defineFlow(
  {
    name: 'generatePostImageFlow',
    inputSchema: GeneratePostImageInputSchema,
    outputSchema: GeneratePostImageOutputSchema,
  },
  async (input: GeneratePostImageInput) => {
    let imagePrompt = `You are an AI social media image generator.
Your primary task is to create an image based on the following detailed visual description: "${input.imageVisualPrompt}".
This image is for a social media post related to the general topic: "${input.postTopic}".

The image must strictly adhere to the following parameters:
- Niche: "${input.niche}"
- Category: "${input.category}"
- Image Style: "${input.imageType}"`;

    if (input.postType) {
      imagePrompt += `\n- Post Type Context: This image is part of a "${input.postType}" post. Consider this for the overall mood or subtle thematic elements, ensuring it complements the main visual description.`;
    }

    if (input.overlayText && input.overlayText.trim() !== '') {
      imagePrompt += `\n\nThe most critical visual element is to feature the following AI-generated hook text directly ON the image: "${input.overlayText}".
The text should be seamlessly integrated into the image's design as if it were a professional social media graphic.
Render the text in an interesting and visually engaging manner, making it a focal point.

Key considerations for the overlay text:
- Typography & Style: Pay close attention to typography to ensure the text is highly readable and enhances the overall image.
  - Color Variation: Creatively apply color variations within the overlay text. For example, you might make one or two key words a different, complementary color from the main text color, or use a subtle gradient if appropriate for the style. This should enhance visual appeal.
  - Font Emphasis: For added visual interest and emphasis, attempt to render approximately two important words from the hook text in a slightly different but harmonious font style (e.g., a bolder weight, a subtle script if the main font is sans-serif, or vice-versa) compared to the rest of the overlay text. This should complement the primary chosen font style if one is specified.
  - Readability: Above all, ensure the text remains clear, legible, and well-contrasted against the image background.
`;

      if (input.overlayFontStyle) {
        imagePrompt += `\n- Primary Text Font Style: The overall text should generally adhere to a style best described as '${input.overlayFontStyle}'. The font emphasis for specific words should be a variation or complement to this primary style.`;
      }
      if (input.overlayAlignment) {
        imagePrompt += `\n- Text Alignment: Position the text on the image according to '${input.overlayAlignment}'. For example, if 'Top Right' is specified, place it in the top-right area. If 'Middle Center', place it centrally.`;
      }
      if (input.overlayFontSize) {
        imagePrompt += `\n- Text Font Size: The text should appear in a '${input.overlayFontSize}' relative size. 'Large' or 'Extra Large' should be very prominent, 'Small' should be more subtle but still readable. 'Medium' is a balanced default.`;
      }
      imagePrompt += `\nConsider the overall image composition to ensure the text placement and styling feel natural and engaging, making the hook an integral and appealing part of the graphic.`;
    } else {
      imagePrompt += `\n\nGenerate a high-quality image based purely on the visual description, niche, category, image type, and post context. No text should be overlaid on this image.`;
    }
    
    imagePrompt += `\nThe overall image composition and style should be suitable for the visual prompt, niche, category, and specified image type. Aim for an engaging, high-quality, and aesthetically pleasing result.`;
    
    const {media} = await ai.generate({
      model: 'googleai/gemini-2.0-flash-exp',
      prompt: [
        {
          text: imagePrompt,
        },
      ],
      config: {
        responseModalities: ['TEXT', 'IMAGE'], 
      },
    });

    if (!media || !media.url) {
      throw new Error('Image generation failed or did not return a valid image URI.');
    }

    return {imageUri: media.url};
  }
);

